### ISSUE TITLE
5.6.4 jammy does not include any Redis modules

### ISSUE THREAD

**Issue by weili-jiang** [sipwise/kamailio-deb-jenkins#12]
There seems to be some packaging problem - I tried to install Kamailio 5.6 from https://deb.kamailio.org but even though it said kamailio-redis-modules were installed, Kamailio couldn't file the .so files.

When I manually inspect the .deb here:
https://deb.kamailio.org/kamailio56/pool/main/k/kamailio/kamailio-redis-modules_5.6.4%2Bubuntu22.04_amd64.deb

There is nothing except documentation (no actual library files):

```
> dpkg --contents kamailio-redis-modules_5.6.4+ubuntu22.04_amd64.deb

drwxr-xr-x root/root         0 2023-02-28 01:46 ./
drwxr-xr-x root/root         0 2023-02-28 01:46 ./usr/
drwxr-xr-x root/root         0 2023-02-28 01:46 ./usr/share/
drwxr-xr-x root/root         0 2023-02-28 01:46 ./usr/share/doc/
drwxr-xr-x root/root         0 2023-02-28 01:46 ./usr/share/doc/kamailio-redis-modules/
-rw-r--r-- root/root       492 2023-02-28 01:46 ./usr/share/doc/kamailio-redis-modules/changelog.Debian.gz
-rw-r--r-- root/root    121021 2023-02-28 01:46 ./usr/share/doc/kamailio-redis-modules/changelog.gz
-rw-r--r-- root/root     15067 2023-02-28 01:46 ./usr/share/doc/kamailio-redis-modules/copyright
```

**Comment by linuxmaniac** [comment]
fixed at https://github.com/kamailio/kamailio/issues/3617
